version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip install --upgrade pip setuptools
      - pip install "pyyaml>=6.0.2" cfn-lint taskcat --quiet

  pre_build:
    commands:
      - echo "=== cfn-lint ==="
      - cfn-lint templates/main.yaml --include-checks W || true
      - cfn-lint templates/network.yaml --include-checks W || true
      - cfn-lint templates/security.yaml --include-checks W || true
      - cfn-lint templates/compute.yaml --include-checks W || true

  build:
    commands:
      - echo "=== taskcat ==="
      - taskcat test run

artifacts:
  files:
    - "**/*"
  discard-paths: no